version: '3.9'

services:
  monitor:
    build: .
    volumes: 
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '.:/usr/src/app'
    environment:
      DYNAMODB_TABLE: my_table
      KEY: asdf
    env_file: .env
    network_mode: host
    depends_on: 
      good:
        condition: service_started
      bad:
        condition: service_healthy

  good:
    build:
      context: test
    command: bundle exec ruby good.rb
    volumes: 
      - './test:/usr/src/app'
    labels:
      com.fenderton.shutdown_over_mem_limit: 'yes'
      com.amazonaws.ecs.task-arn: 'asdf-good'
    deploy:
      resources:
        reservations:
          memory: 128M

  bad:
    build:
      context: test
    command: bundle exec ruby bad.rb
    volumes: 
      - './test:/usr/src/app'
    labels:
      com.fenderton.shutdown_over_mem_limit: 'yes'
      com.amazonaws.ecs.task-arn: 'asdf-bad'
    ports:
      - 3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/ping"]
    deploy:
      resources:
        reservations:
          memory: 8M
